// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU_P-qoKZkFYAE761nLwN7YLxtxhobbKs',
    appId: '1:312021980699:web:2e894db72452ea02a9cabe',
    messagingSenderId: '312021980699',
    projectId: 'fire-ca14d',
    authDomain: 'fire-ca14d.firebaseapp.com',
    storageBucket: 'fire-ca14d.appspot.com',
    measurementId: 'G-T5H56LDB1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl8cHhI1ik70JQ3XFq1OZrUuuYlktXJYE',
    appId: '1:312021980699:android:549296bd8d81dcf0a9cabe',
    messagingSenderId: '312021980699',
    projectId: 'fire-ca14d',
    storageBucket: 'fire-ca14d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHlYwP44j59rD0i7PMKP1x3UtGbxSyFQ4',
    appId: '1:312021980699:ios:5b549235deeba735a9cabe',
    messagingSenderId: '312021980699',
    projectId: 'fire-ca14d',
    storageBucket: 'fire-ca14d.appspot.com',
    iosClientId: '312021980699-emapaitlojj9k5drigqq0e9rsegrdi9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.jan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHlYwP44j59rD0i7PMKP1x3UtGbxSyFQ4',
    appId: '1:312021980699:ios:5b549235deeba735a9cabe',
    messagingSenderId: '312021980699',
    projectId: 'fire-ca14d',
    storageBucket: 'fire-ca14d.appspot.com',
    iosClientId: '312021980699-emapaitlojj9k5drigqq0e9rsegrdi9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.jan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU_P-qoKZkFYAE761nLwN7YLxtxhobbKs',
    appId: '1:312021980699:web:cb55070c30b49614a9cabe',
    messagingSenderId: '312021980699',
    projectId: 'fire-ca14d',
    authDomain: 'fire-ca14d.firebaseapp.com',
    storageBucket: 'fire-ca14d.appspot.com',
    measurementId: 'G-YFLZX741G6',
  );
}
